### ISSUE TITLE
pipenv install fails

### ISSUE THREAD

**Issue by Adarshjayan3032** [cmdmnt/commandment#20]
pipenv install fails please help.

pipenv, version 2018.7.1
Rover:commandment-master adarsh$ pipenv install
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project...
Pipfile: /Users/one/Desktop/ram/commandment-master/Pipfile
Using /usr/local/opt/python/bin/python3.7 (3.7.0) to create virtualenv...
⠋Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/pipenv/pew/__main__.py", line 8, in <module>
    import pew
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/pew/__init__.py", line 3, in <module>
    from . import pew
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/pew/pew.py", line 44, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/pew/_utils.py", line 25, in <module>
    encoding = locale.getlocale()[1] or 'ascii'
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 587, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 495, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

Virtualenv location: 
Installing -e git+https://github.com/cmdmnt/bixar.git#egg=bixar...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1971, in do_install
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1445, in pip_install
    quoted_pip = which_pip(allow_global=allow_global)
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1502, in which_pip
    return which('pip')
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 115, in which
    p = os.path.join(location, 'bin', command)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by mosen** [comment]
Unknown locale is pretty strange to get from pipenv. What’s your language set to?

**Comment by Adarshjayan3032** [comment]
Programmin language Python 3.7.0

Os language - English In
