### ISSUE TITLE
SCEP testing...

### ISSUE THREAD

**Issue by shahasachin** [cmdmnt/commandment#9]
Hello Jesse,

I have configured Commandment on Windows 7 successfully, created Web Server Certificate and APNS certificate.

Query:
Is SCEP functionality is implemented in this project?
If yes than how to test it please provide steps.

**Comment by shahasachin** [comment]
After configuring Commandment, load runserver.py in command prompt window and another command prompt window when try to load runscep.py it throws following exception:

(commandment-venv) C:\Python27\commandment-master>python runscep.py
Traceback (most recent call last):
  File "runscep.py", line 48, in <module>
    init_libcrypto(app.config.get('LIBCRYPTO_PATH'))
  File "C:\Python27\commandment-master\commandment\scep\glue.py", line 348, in init_libcrypto
    libcrypto = CDLL(lib_path)
  File "c:\python27\Lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: expected string or Unicode object, NoneType found

Am I missing any step or is any configuration missing?
